" Use mouse
set mouse=a

" Don't wrap by default
set nowrap

" Use 4 spaces for indenting
set expandtab
set shiftwidth=4
set softtabstop=4

" Always  set auto indenting on
set autoindent

" Select when using the mouse
set selectmode=mouse

" Set status line
set statusline=[%02n]\ %f\ %(\[%M%R%H]%)%=\ %4l,%02c%2V\ %P%*        
