#!/usr/bin/env bash
#
# Must be executed with root or sudo.
#

cat <<'EOT'> /usr/local/bin/env-anaconda3.sh
#!/usr/bin/env bash
ANACONDA3_HOME=/opt/anaconda3
export ANACONDA3_HOME
 
PATH=$ANACONDA3_HOME/bin/:$PATH
export PATH
EOT
  
chmod +x /usr/local/bin/env-anaconda3.sh
  
cat <<'EOT'> /etc/profile.d/anaconda3.sh
alias env-anaconda3='source /usr/local/bin/env-anaconda3.sh'
EOT
  
echo "You can do: source /etc/profile.d/anaconda3.sh"
