#!/usr/bin/env bash
#
# Must be executed with root or sudo.
#

cat <<'EOT'> /usr/local/bin/env-miniconda3.sh
#!/usr/bin/env bash
MINICONDA3_HOME=/opt/miniconda3
export MINICONDA3_HOME
 
PATH=$MINICONDA3_HOME/bin/:$PATH
export PATH
EOT
  
chmod +x /usr/local/bin/env-miniconda3.sh
  
cat <<'EOT'> /etc/profile.d/miniconda3.sh
alias env-miniconda3='source /usr/local/bin/env-miniconda3.sh'
EOT
  
echo "You can do: source /etc/profile.d/miniconda3.sh"
