#!/usr/bin/env bash
#
# Jailer Project Page: http://jailer.sourceforge.net/
# 
# Jailer does not work well when installed in shared mode at /opt/.
#

INSTALL_BASE=${HOME}/app/
JAILER_URL=https://cfhcable.dl.sourceforge.net/project/jailer/v7.8.2/jailer_7.8.2.zip

if [ ! -d ${INSTALL_BASE}/jailer ]
then

    wget -O /tmp/jailer.zip $JAILER_URL
    unzip /tmp/jailer.zip

    mv jailer ${INSTALL_BASE}
    #chown -R root:root /opt/jailer
    #chmod -R  a+rX /opt/jailer

    rm /tmp/jailer.zip
fi


# Install Launcher

cp -u ./resources/jailer-*.desktop ~/.local/share/applications

