#!/usr/bin/env bash

INSTALL_BASE=/opt/
POSTMAN_URL=https://dl.pstmn.io/download/latest/linux64

# Make sure only root can run our script

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Install if not already done

if [ ! -d ${INSTALL_BASE}/Postman ]
then

    wget -O /tmp/postman.tar.gz $POSTMAN_URL
    tar -vxzf /tmp/postman.tar.gz

    mv Postman ${INSTALL_BASE}
    chown -R root:root /opt/Postman
    chmod -R  a+rX /opt/Postman

    rm /tmp/postman.tar.gz
fi


# Install Launcher

cp -u ./resources/postman.desktop /usr/share/applications
chmod 644 /usr/share/applications/*.desktop

