#!/usr/bin/env bash

docker run --rm -it  \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -v $HOME:/opt/gitkraken/data \
    -v $HOME/.gitkraken:/opt/gitkraken/config \
    -e USER_ID=$(id -u) \
    -e GROUP_ID=$(id -g) \
    --privileged \
    -v=/dev/dri:/dev/dri:rw \
    --entrypoint=bash \
    local/gitkraken   

