#!/bin/bash

docker create --name boostnote \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -v $HOME:/boostnote-data \
    -e USER_ID=$(id -u) \
    -e GROUP_ID=$(id -g) \
    --privileged \
    -v=/dev/dri:/dev/dri:rw \
    local/boostnote
